name: publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  UV_VERSION: 0.7.21

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: "${{ steps.contains_tag.outputs.retval }}"
    steps:
      # TODO: remove this and the `git branch -a` when the following PR
      # is merged and released:
      #   https://github.com/rickstaa/action-contains-tag/pull/18
      - name: git config --global remote.origin.followRemoteHEAD never
        run: git config --global remote.origin.followRemoteHEAD never

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - uses: rickstaa/action-contains-tag@a9ff27d505ba2bf074a2ebb48b208e76d35ff308  # v1.2.10
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref_name }}"

  tests:
    name: tests
    needs: on-main-branch-check
    if: "${{ needs.on-main-branch-check.outputs.on_main == 'true' }}"
    uses: "./.github/workflows/python_package.yml"

  build-wheels:
    name: build wheels
    needs: tests
    uses: "./.github/workflows/wheels.yml"

  build-sdist:
    name: build source distribution
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          python-version: 3.12
          enable-cache: 'true'
          cache-suffix: 3.12

      - name: Install dependencies
        run: uv sync --locked

      - name: Build package
        run: uv build --sdist

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: pybedlite-sdist
          path: dist/*.tar.gz

  # TODO: update to use `uv publish`
  publish-to-pypi:
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          path: packages
          pattern: 'pybedlite-*'
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          packages-dir: packages/
          skip-existing: true
          verbose: true

  make-changelog:
    runs-on: ubuntu-latest
    needs: publish-to-pypi
    outputs:
      release_body: "${{ steps.git-cliff.outputs.content }}"
    steps:
      - name: Checkout the Repository at the Tagged Commit
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
          ref: "${{ github.ref_name }}"

      - name: Generate a Changelog
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7  # v4.4.2
        id: git-cliff
        with:
          config: pyproject.toml
          args: --latest --verbose
        env:
          GITHUB_REPO: "${{ github.repository }}"

  make-github-release:
    runs-on: ubuntu-latest
    environment: github
    permissions:
      contents: write
      pull-requests: read
    needs: make-changelog
    steps:
      - name: Download the sdist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8  # v2.3.2
        with:
          name: '${{ github.ref_name }}'
          body: '${{ needs.make-changelog.outputs.release_body }}'
          draft: false
          prerelease: false
