name: Code checks

on:
  push:
  workflow_call:

env:
  UV_VERSION: 0.7.21

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          python-version: "${{ matrix.PYTHON_VERSION }}"
          enable-cache: "true"
          cache-suffix: "${{ matrix.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Test the library
        run: |
          uv run poe check-all

      - name: Run docs
        shell: bash
        run: |
          set -euo pipefail
          uv run --directory docs --group docs make html

      - name: Upload code coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
