name: Build wheels for multiple platforms

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.python }}-${{ matrix.target }}-${{ matrix.arch }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["cp38", "cp39", "cp310", "cp311"]
        include:
          - os: ubuntu-latest
            target: manylinux
            arch: x86_64
          - os: ubuntu-latest
            target: musllinux
            arch: x86_64
          - os: ubuntu-latest
            target: manylinux
            arch: aarch64
          - os: ubuntu-latest
            target: musllinux
            arch: aarch64
          - os: macos-latest
            target: macosx
            arch: x86_64
          - os: macos-latest
            target: macosx
            cibw_archs: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.target }}_${{ matrix.arch }}
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
