name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build multiarch Python3 wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: 3.13

      - name: Build wheels
        run: pip wheel --no-deps -w /tmp/wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: pybedlite-wheel
          path: /tmp/wheelhouse/pybedlite*.whl
          if-no-files-found: error
