name: Build wheels for multiple platforms

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.python }}-${{ matrix.platform.target }}_${{ matrix.platform.arch }} on ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        python: [cp38, cp39, cp310, cp311]
        platform:
          - os: ubuntu-latest
            target: manylinux
            arch: x86_64
          - os: ubuntu-latest
            target: musllinux
            arch: x86_64
          # These don't work right now - they just hang while pulling the build image from quay.
          # If this doesn't resolve itself, we could try to configure different images:
          # https://cibuildwheel.readthedocs.io/en/stable/options/.
          #- os: ubuntu-latest
          #  target: manylinux
          #  arch: aarch64
          #- os: ubuntu-latest
          #  target: musllinux
          #  arch: aarch64
          - os: macos-latest
            target: macosx
            arch: x86_64
          - os: macos-latest
            target: macosx
            arch: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: ${{ matrix.platform.arch }}
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform.target }}_${{ matrix.platform.arch }}
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl
          if-no-files-found: error
