name: Build wheels for multiple platforms

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["cp38-* cp-39* cp-310* cp-311*"]
        include:
          - os: ubuntu-latest
            cibw_archs: "x86_64 aarch64"
          - os: macos-latest
            cibw_archs: "x86_64 arm64"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: ${{ matrix.python }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
