name: Build wheels for multiple platforms

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.cibw_build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: x86_64
            cibw_build:
              - cp38-manylinux_x86_64
              - cp38-musllinux_x86_64
              - cp39-manylinux_x86_64
              - cp39-musllinux_x86_64
              - cp310-manylinux_x86_64
              - cp310-musllinux_x86_64
              - cp311-manylinux_x86_64
              - cp311-musllinux_x86_64
          - os: ubuntu-latest
            cibw_archs: aarch64
            cibw_build:
              - cp38-manylinux_aarch64
              - cp38-musllinux_aarch64
              - cp39-manylinux_aarch64
              - cp39-musllinux_aarch64
              - cp310-manylinux_aarch64
              - cp310-musllinux_aarch64
              - cp311-manylinux_aarch64
              - cp311-musllinux_aarch64
          - os: macos-latest
            cibw_archs: x86_64
            cibw_build:
              - cp38-macosx_x86_64
              - cp39-macosx_x86_64
              - cp310-macosx_x86_64
              - cp311-macosx_x86_64
          - os: macos-latest
            cibw_archs: arm64
            cibw_build:
              - cp38-macosx_arm64
              - cp39-macosx_arm64
              - cp310-macosx_arm64
              - cp311-macosx_arm64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
